version: '3'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres-pet-shop
    ports: 
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_USERNAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data  